#!/bin/sh

set -e

case "$1" in
    remove|purge)

	if which invoke-rc.d >/dev/null 2>&1; then
		invoke-rc.d zabbix-agent restart
	else
		/etc/init.d/zabbix-agent restart
	fi

	;;

    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
	;;

    *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
esac

#DEBHELPER#

exit 0

