#!/bin/sh

set -e

case "$1" in
    remove|purge)

        grep -v 'zabbix-check-sshkey' /etc/sudoers > /etc/.sudoers
	mv /etc/.sudoers /etc/sudoers
	chmod 440 /etc/sudoers

        if which invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d zabbix-agent stop || true
            invoke-rc.d zabbix-agent start || true
        else
            /etc/init.d/zabbix-agent stop || true
            /etc/init.d/zabbix-agent start || true
        fi
	;;

    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
	;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#

exit 0

