#!/bin/sh -e

case "$1" in
    purge|remove)
		#remove old version of sudo rigets (pre 1:0.4)
		if grep -q 'zabbix_check_smart_get.py' /etc/sudoers; then
			grep -v 'zabbix_check_smart_get.py' /etc/sudoers > /etc/.sudoers
			mv /etc/.sudoers /etc/sudoers
			chmod 440 /etc/sudoers
		fi

		if which invoke-rc.d >/dev/null 2>&1; then
		    invoke-rc.d zabbix-agent stop || true
		    invoke-rc.d zabbix-agent start || true
		else
		    /etc/init.d/zabbix-agent stop || true
		    /etc/init.d/zabbix-agent start || true
		fi
        ;;

    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

exit 0
