#!/bin/sh -e

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
    ;;
    remove|purge)

    grep -v 'zabbix_check_smart_get.py' /etc/sudoers > /etc/.sudoers
    mv /etc/.sudoers /etc/sudoers
    chmod 440 /etc/sudoers

    if which invoke-rc.d >/dev/null 2>&1; then
        invoke-rc.d zabbix-agent stop || true
        invoke-rc.d zabbix-agent start
    else
        /etc/init.d/zabbix-agent stop || true
        /etc/init.d/zabbix-agent start
    fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac
exit 0
