#!/bin/sh

set -e

case "$1" in
    remove|purge)

        rm -rf /usr/share/zabbix/dpkg || true

    ;;

    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#

exit 0

